/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JTextField;



import java.util.Iterator;
import static javafx.scene.transform.Transform.scale;
import static javax.swing.Spring.scale;
import org.apache.pdfbox.exceptions.COSVisitorException;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentCatalog;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDResources;
import org.apache.pdfbox.pdmodel.edit.PDPageContentStream;
import org.apache.pdfbox.pdmodel.graphics.xobject.PDPixelMap;
import org.apache.pdfbox.pdmodel.graphics.xobject.PDXObjectImage;
/**
 *
 * @author RojeruSan
 */
public class PNL_Personalizacion extends javax.swing.JPanel {

    private List<JTextField> lista_nombre_seccion, lista_rango_inferior_seccion, lista_rango_superior_seccion;
    String ruta_pdf;
    
    public PNL_Personalizacion() {
        initComponents();        
        lista_nombre_seccion = new ArrayList<>();
        lista_rango_inferior_seccion = new ArrayList<>();
        lista_rango_superior_seccion = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtnum_secciones = new javax.swing.JTextField();
        btnSeccion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        Panel_nom_seccion = new javax.swing.JPanel();
        Panel_rango_inferior_seccion = new javax.swing.JPanel();
        Panel_rango_superior_seccion = new javax.swing.JPanel();
        btn_generar_secciones = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/chat.png"))); // NOI18N
        jLabel7.setText("Personalización");

        btnSeccion.setText("Crear Secciones");
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnum_secciones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeccion))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnum_secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeccion))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Panel_nom_seccion.setLayout(new java.awt.GridLayout(10, 0));
        jPanel6.add(Panel_nom_seccion);

        Panel_rango_inferior_seccion.setLayout(new java.awt.GridLayout(10, 0));
        jPanel6.add(Panel_rango_inferior_seccion);

        Panel_rango_superior_seccion.setLayout(new java.awt.GridLayout(10, 0));
        jPanel6.add(Panel_rango_superior_seccion);

        jScrollPane2.setViewportView(jPanel6);

        btn_generar_secciones.setText("Generar Secciones");
        btn_generar_secciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generar_seccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_generar_secciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn_generar_secciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
        int numSecciones = 0;        
        
        Panel_nom_seccion.removeAll();
        Panel_rango_superior_seccion.removeAll();
        Panel_rango_inferior_seccion.removeAll();
        
        lista_nombre_seccion.clear();
        
        numSecciones = Integer.parseInt(txtnum_secciones.getText());
        
        for (int i = 0; i <= numSecciones; i++) {
            
            if(i == 0){
                Label lbl_nomb_seccion = new Label("Nombre de la Sección");
                Label lbl_rango_inferior_seccion = new Label("De");
                Label lbl_rango_superior_seccion = new Label("Hasta");
                
                Panel_nom_seccion.add(lbl_nomb_seccion);                
                Panel_nom_seccion.updateUI();
                
                Panel_rango_inferior_seccion.add(lbl_rango_inferior_seccion);
                Panel_rango_inferior_seccion.updateUI();      
                
                Panel_rango_superior_seccion.add(lbl_rango_superior_seccion);
                Panel_rango_superior_seccion.updateUI();        
             
            }else{
                JTextField nombre_seccion = new JTextField("",10);
                JTextField rango_inferior_seccion = new JTextField("",5);
                JTextField rango_superior_seccion = new JTextField("",5);
  
                Panel_nom_seccion.add(nombre_seccion);
                lista_nombre_seccion.add(nombre_seccion);
                Panel_nom_seccion.updateUI();                   
                
                Panel_rango_inferior_seccion.add(rango_inferior_seccion);
                lista_rango_inferior_seccion.add(rango_inferior_seccion);
                Panel_rango_inferior_seccion.updateUI(); 

                Panel_rango_superior_seccion.add(rango_superior_seccion);
                lista_rango_superior_seccion.add(rango_superior_seccion);
                Panel_rango_superior_seccion.updateUI();
            }            
        }
        txtnum_secciones.setText("");

    }//GEN-LAST:event_btnSeccionActionPerformed

    private void btn_generar_seccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generar_seccionesActionPerformed
               
        String pdfFilePath = "C:/Users/encis/OneDrive/Escritorio/Documentos/pdf/instrucciones.pdf";         

        PDDocument document = null; 
        try {
            document = PDDocument.load(pdfFilePath);
        } catch (IOException ex) {
            Logger.getLogger(PNL_Personalizacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            addImageToPage(document, lista_nombre_seccion, lista_rango_inferior_seccion, lista_rango_superior_seccion);
        } catch (IOException ex) {
            Logger.getLogger(PNL_Personalizacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {         
            document.save("C:/Users/encis/OneDrive/Escritorio/Documentos/pdf/prueba-marca-de-agua.pdf");
        } catch (IOException ex) {
            Logger.getLogger(PNL_Personalizacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (COSVisitorException ex) {
            Logger.getLogger(PNL_Personalizacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_generar_seccionesActionPerformed

    public static void addImageToPage(PDDocument document, List<JTextField> lista_nombre_seccion, List<JTextField> lista_rango_inferior_seccion, List<JTextField> lista_rango_superior_seccion) throws IOException { 
        int cantidad_secciones = lista_nombre_seccion.size();
        BufferedImage image = null; 
        int pdfpage=0;
        for (int i = 0; i < cantidad_secciones; i++) {
            String nomb_seccion = lista_nombre_seccion.get(i).getText();
            int inicio_pagina = Integer.parseInt(lista_rango_inferior_seccion.get(i).getText());
            int final_pagina = Integer.parseInt(lista_rango_superior_seccion.get(i).getText()); 
                        
            int cont=1;            
            int cantidad_paginas = final_pagina - inicio_pagina + 1;   
            
            for (int j = inicio_pagina; j <= final_pagina; j++) {   
                try {
                    image = ImageIO.read(new File( "C:/Users/encis/OneDrive/Escritorio/Documentos/imágenes/simbolo.jpeg"));              
                    Graphics g = image.getGraphics(); 
                    Font myFont = new Font ("Courier New", 1, 55);
                    g.setFont(myFont); 
                    g.setColor(Color.BLACK);
                    g.drawString(nomb_seccion, 70, 130); 
                    g.drawString(""+cont, 90, 270); 
                    g.drawString(""+cantidad_paginas, 230, 270); 
                    g.dispose(); 
                    cont++;    
                                        
                    BufferedImage tmp_image = image;
                    BufferedImage image2 = new BufferedImage(tmp_image.getWidth(), tmp_image.getHeight(), BufferedImage.TYPE_4BYTE_ABGR);   
                    image2.createGraphics().drawRenderedImage(tmp_image, null); 
                    
                    PDXObjectImage ximage = new PDPixelMap(document, image2); 
                    PDPage page = (PDPage)document.getDocumentCatalog().getAllPages().get(pdfpage); 
                    
                    PDPageContentStream contentStream = new PDPageContentStream(document, page, true, true); 
                    contentStream.drawXObject(ximage, 0, 600, ximage.getWidth()*0.5f, ximage.getHeight()*0.5f); 
                    contentStream.close(); 
                    
                    pdfpage++;
                } catch (IOException ex) {
                    Logger.getLogger(PNL_Personalizacion.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        }
            
    }       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_nom_seccion;
    private javax.swing.JPanel Panel_rango_inferior_seccion;
    private javax.swing.JPanel Panel_rango_superior_seccion;
    private javax.swing.JButton btnSeccion;
    private javax.swing.JButton btn_generar_secciones;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtnum_secciones;
    // End of variables declaration//GEN-END:variables
}
